apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-python-app
spec:
 replicas: 3
 selector:
 matchLabels:
 app: my-python-app
 template:
 metadata:
 labels:
 app: my-python-app
 spec:
 containers:
 - name: my-python-app
 image: matej3/my-python-app:${v1}
 ports:
 - containerPort: 80
 apiVersion: v1
kind: Service
metadata:
 name: my-python-app-service
spec:
 selector:
 app: my-python-app
 ports:
 - protocol: TCP
 port: 80
 targetPort: 80
 type: LoadBalancer
